language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.7
notifications:
    email: false
services:
    - redis-server

before_install:
    - pip install pycodestyle
    - pip install pydocstyle
    - pip install pytest

install:
    - python -m pip install .

script:
    # Run pycodestyle on all .py files in all subfolders
    - pycodestyle --max-line-length=99 .
    - pydocstyle --convention=numpy .

    # Run tests
    - export PYTHONPATH=.:$PYTHONPATH
    - pytest -s
